#!/usr/bin/env python3
"""Regenerate db/mob_db.yml from rAthena's stock mob_db.yml.

Usage:
    ./generate.py <path to rathena mob_db.yml> [--out db/mob_db.yml]

Or, with the vendor tree fetched beside the app:
    ./generate.py ../../../vendor/rathena/db/re/mob_db.yml

For every non-MVP monster whose Drops table contains a card, this writes an
override entry that targets the card's existing slot by Index and flips
StealProtected: false. That is the whole change; rAthena's `pc_steal_item`
filters on that flag and does the rest.

Since rAthena's MobDatabase::parseDropNode now treats Item/Rate/RandomOptionGroup
as optional on an override that names an existing Index, the generated file
spells only Index and StealProtected -- the stock Item and Rate stay whatever
rAthena ships them as, which is also the whole point of using `db/import`.

MVPs are excluded. "MVP" here is the strict rAthena meaning: `MvpDrops:` is
present, or `Modes.Mvp: true` is set. Mini-bosses (Angeling, Ghostring,
Vagabond Wolf and friends) are `Class: Boss` without either, so their cards
stay in.

PyYAML is the only requirement: `pip install pyyaml`.
"""

import argparse
import sys
from pathlib import Path

import yaml


# Per-mob Rate: overrides. The generator writes a Rate: line for each entry
# listed here, keyed by the mob's Id. Leave a mob out and only its stock drop
# rate is used (both on-kill and Steal track whatever rAthena ships). This
# applies to the override's Rate field, so a value here changes both the
# on-kill drop and the Steal weighting -- there is no field that affects
# only Steal.
#
# rAthena's rate unit is 0.01%, so 10000 = 100%.
RATE_OVERRIDES: dict[int, int] = {}


def strip_yaml_comments(text: str) -> str:
    """Drop whole-line comments. PyYAML handles in-line ones."""
    return "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("#"))


def is_mvp(mob: dict) -> bool:
    """True for actual MVPs -- the ones that give MvpExp and set the Mvp
    mode flag. `Class: Boss` on its own is not enough: Angeling, Deviling,
    Ghostring, Vagabond Wolf and dozens of other mini-bosses are Class:
    Boss but not MVPs, and their cards are precisely the ones a Thief on a
    stealth run wants."""
    if "MvpDrops" in mob:
        return True
    modes = mob.get("Modes") or {}
    if isinstance(modes, dict) and modes.get("Mvp"):
        return True
    return False


def find_card_drop(mob: dict):
    """Return (index, aegis_name) for the mob's card drop, or None if the
    mob has none. Index is the drop's explicit `Index:` if present,
    otherwise its position in the list -- which is how rAthena assigns
    slots when they are not spelled out. The aegis name is only kept for
    the comment on the output entry; the override itself does not spell
    it, so a rename on the stock side cannot drift the mod silently.
    """
    drops = mob.get("Drops") or []
    for pos, drop in enumerate(drops):
        item = drop.get("Item", "")
        if not item.endswith("_Card"):
            continue
        return drop.get("Index", pos), item
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("source", type=Path, help="rAthena mob_db.yml")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).parent / "db" / "mob_db.yml",
                    help="output file (default: db/mob_db.yml next to this script)")
    args = ap.parse_args()

    doc = yaml.safe_load(strip_yaml_comments(args.source.read_text()))
    body = doc.get("Body") or []

    entries = []
    skipped_mvp = 0
    no_card = 0

    for mob in body:
        if mob.get("Id") is None:
            continue
        if is_mvp(mob):
            skipped_mvp += 1
            continue
        found = find_card_drop(mob)
        if found is None:
            no_card += 1
            continue
        idx, card = found
        entries.append((mob["Id"], mob.get("AegisName", "?"),
                        mob.get("Name", "?"), idx, card))

    entries.sort(key=lambda e: e[0])

    header = [
        "# Generated by generate.py against rAthena's stock mob_db.yml --",
        "# do not hand-edit. Rerun the generator when the rAthena vendor",
        "# pin moves. See README.md.",
        "#",
        "# For every non-MVP monster that already drops a card, this file",
        "# flips StealProtected: false on the exact slot the card sits at.",
        "# Item and Rate are not restated: MobDatabase::parseDropNode treats",
        "# them as optional on an override targeting an existing Index, so",
        "# the stock values stay whatever rAthena ships. rAthena's",
        "# pc_steal_item filters out steal_protected drops; flipping the",
        "# flag is the whole change.",
        "Header:",
        "  Type: MOB_DB",
        "  Version: 5",
        "",
        "Body:",
    ]

    body_lines = []
    for mob_id, aegis, name, idx, card in entries:
        body_lines.append(f"  - Id: {mob_id} # {name} ({aegis}) -- {card}")
        body_lines.append("    Drops:")
        body_lines.append(f"      - Index: {idx}")
        if mob_id in RATE_OVERRIDES:
            body_lines.append(f"        Rate: {RATE_OVERRIDES[mob_id]}")
        body_lines.append("        StealProtected: false")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(header + body_lines) + "\n")

    print(f"mobs with a card drop, non-MVP: {len(entries)}", file=sys.stderr)
    print(f"skipped MVPs:                  {skipped_mvp}", file=sys.stderr)
    print(f"mobs without a card:           {no_card}", file=sys.stderr)
    print(f"wrote:                         {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
